const headerFormat={
    orderDetails: [
        { name: "Order No", prop: "orderNo" },
        { name: "Order Delivery Date", prop: "orderDeliveryDate" },
        { name: "Category", prop: "designCategory" },
        { name: "Model", prop: "designModel" },
        { name: "Length", prop: "length" },
        { name: "Chest", prop: "chest" },
        { name: "Waist", prop: "waist" },
        { name: "Hipps", prop: "hipps" },
        { name: "Bottom", prop: "bottom" },
        { name: "Sleeve", prop: "sleeve" },
        { name: "Sleeve Loose", prop: "sleeveLoose" },
        { name: "Shoulder", prop: "shoulder" },
        { name: "Neck", prop: "neck" },
        { name: "BackDown", prop: "backDown" },
        { name: "Extra", prop: "extra" },
        { name: "Size", prop: "size" },
        { name: "Deep", prop: "deep" },
        { name: "Cuff", prop: "cuff" },
        { name: "Description", prop: "description" },
        { name: "Work Type", prop: "workType" },
        { name: "Order Status", prop: "orderStatus" },
        { name: "Measurement Status", prop: "measurementStatus" },
        { name: "Crystal", prop: "crystal" },
        { name: "Crystal Price", prop: "crystalPrice" },
        { name: "Price", prop: "price" },
        { name: "Sub Total Amount", prop: "subTotalAmount" },
        { name: "VAT", prop: "vat" },
        { name: "VAT Amount", prop: "vatAmount" },
        { name: "Total Amount", prop: "totalAmount" },
        { name: "Status", prop: "status" },
        { name: "Cancelled by", prop: "updatedBy" },
        { name: "Cancelled On", prop: "updatedAt" },
        { name: "Cancel Note", prop: "note" },
    ]
}
export {headerFormat};