const apiPrfix = "api";
export const apiUrls = {
    accountController:{
        getSummarReport:`${apiPrfix}/account/get/summary-report`,
    },
    permissionController:{
        getPermissions: `${apiPrfix}/permission?roleId=`,
        getPermissionResource: `${apiPrfix}/permission/resource`,
        getRole: `${apiPrfix}/permission/roles`,
        updatePermissions: `${apiPrfix}/permission`,
        getPermissionByRoleName:`${apiPrfix}/permission/role/`,
    }, 
    expenseController: {
        addExpense: `${apiPrfix}/expense`,
        updateExpense: `${apiPrfix}/expense`,
        deleteExpense: `${apiPrfix}/expense/`,
        getExpense: `${apiPrfix}/expense/get/`,
        getExpenseNo: `${apiPrfix}/expense/get/expense-no`,
        getAllExpense: `${apiPrfix}/expense`,
        searchExpense: `${apiPrfix}/expense/search`,
        addExpenseType: `${apiPrfix}/expense/type`,
        updateExpenseType: `${apiPrfix}/expense/type`,
        deleteExpenseType: `${apiPrfix}/expense/type/`,
        getExpenseType: `${apiPrfix}/expense/type/get/`,
        getAllExpenseType: `${apiPrfix}/expense/type`,
        searchExpenseType: `${apiPrfix}/expense/type/search`,
        addExpenseName: `${apiPrfix}/expense/name`,
        updateExpenseName: `${apiPrfix}/expense/name`,
        deleteExpenseName: `${apiPrfix}/expense/name/`,
        getExpenseName: `${apiPrfix}/expense/name/get/`,
        getAllExpenseName: `${apiPrfix}/expense/name`,
        searchExpenseName: `${apiPrfix}/expense/name/search`,
        addExpenseCompany: `${apiPrfix}/expense/company`,
        updateExpenseCompany: `${apiPrfix}/expense/company`,
        deleteExpenseCompany: `${apiPrfix}/expense/company/`,
        getExpenseCompany: `${apiPrfix}/expense/company/get/`,
        getAllExpenseCompany: `${apiPrfix}/expense/company`,
        searchExpenseCompany: `${apiPrfix}/expense/company/search`
    },
    authController: {
        token: `${apiPrfix}/user/token/login`,
        changePassword:`${apiPrfix}/user/password`,
        getUsers:`${apiPrfix}/users`,
    },
    dashboardController:{
        getDashboard:`${apiPrfix}/dashboard`,
        getWeeklySale:`${apiPrfix}/dashboard/get/weekly-sales`,
        getMonthlySale:`${apiPrfix}/dashboard/get/monthly-sales`,
        getDailySale:`${apiPrfix}/dashboard/get/daily-sales`,
        getEmpDashboard:`${apiPrfix}/dashboard/get/employee`,
        getOrderDashboard:`${apiPrfix}/dashboard/get/order`,
    },
    customerController: {
        add: `${apiPrfix}/customers`,
        update: `${apiPrfix}/customers`,
        delete: `${apiPrfix}/customers/`,
        get: `${apiPrfix}/customers/get/`,
        getAll: `${apiPrfix}/customers`,
        getByContactNo: `${apiPrfix}/customers/get/by-contact/`,
        search: `${apiPrfix}/customers/search`,
        getStatement:`${apiPrfix}/customers/get/statement?contactNo=`,
        addAdvancePayment:`${apiPrfix}/customers/add/advance-amount`
    },
    employeeController: {
        add: `${apiPrfix}/employees`,
        update: `${apiPrfix}/employees`,
        delete: `${apiPrfix}/employees/`,
        get: `${apiPrfix}/employees/get/`,
        getAll: `${apiPrfix}/employees`,
        search: `${apiPrfix}/employees/search`, 
        searchAll: `${apiPrfix}/employees/search/all?searchTearm=`,
        alert:`${apiPrfix}/employees/send/alert/`,
        getAllActiveDeactiveEmp:`${apiPrfix}/employees/get/active-emp`,
        ActiveDeactiveEmp:`${apiPrfix}/employees/update/active-emp`
    },
    employeeAdvancePaymentController: {
        add: `${apiPrfix}/employee-advance-payment`,
        update: `${apiPrfix}/employee-advance-payment`,
        delete: `${apiPrfix}/employee-advance-payment/`,
        get: `${apiPrfix}/employee-advance-payment/get/`,
        getAll: `${apiPrfix}/employee-advance-payment`,
        search: `${apiPrfix}/employee-advance-payment/search`,
        getStatement: `${apiPrfix}/employee-advance-payment/statement/`
    },
    productController: {
        add: `${apiPrfix}/product`,
        update: `${apiPrfix}/product`,
        delete: `${apiPrfix}/product/`,
        get: `${apiPrfix}/product/get/`,
        getAll: `${apiPrfix}/product`,
        search: `${apiPrfix}/product/search`,
        addType: `${apiPrfix}/product-type`,
        updateType: `${apiPrfix}/product-type`,
        deleteType: `${apiPrfix}/product-type/`,
        getType: `${apiPrfix}/product-type/get/`,
        getAllType: `${apiPrfix}/product-type`,
        searchType: `${apiPrfix}/product-type/search`,
    },
    supplierController: {
        add: `${apiPrfix}/suppliers`,
        update: `${apiPrfix}/suppliers`,
        delete: `${apiPrfix}/suppliers/`,
        get: `${apiPrfix}/suppliers/get/`,
        getAll: `${apiPrfix}/suppliers`,
        search: `${apiPrfix}/suppliers/search`,
    },
    holidayController: {
        addHoliday: `${apiPrfix}/holidays`,
        updateHoliday: `${apiPrfix}/holidays`,
        deleteHoliday: `${apiPrfix}/holidays/`,
        getHoliday: `${apiPrfix}/holidays/get/`,
        isHoliday: `${apiPrfix}/holidays/get/is-holiday`,
        getHolidayByDate: `${apiPrfix}/holidays/get/by-date`,
        getHolidayByMonthYear: `${apiPrfix}/holidays/get/by-month-year/`,
        getAllHoliday: `${apiPrfix}/holidays`,
        searchHoliday: `${apiPrfix}/holidays/search`,
        addHolidayName: `${apiPrfix}/holidays/name`,
        updateHolidayName: `${apiPrfix}/holidays/name`,
        deleteHolidayName: `${apiPrfix}/holidays/name/`,
        getHolidayName: `${apiPrfix}/holidays/name/get/`,
        getAllHolidayName: `${apiPrfix}/holidays/name`,
        searchHolidayName: `${apiPrfix}/holidays/name/search`,
        addHolidayType: `${apiPrfix}/holidays/type`,
        updateHolidayType: `${apiPrfix}/holidays/type`,
        deleteHolidayType: `${apiPrfix}/holidays/type/`,
        getHolidayType: `${apiPrfix}/holidays/type/get/`,
        getAllHolidayType: `${apiPrfix}/holidays/type`,
        searchHolidayType: `${apiPrfix}/holidays/type/search`
    },
    monthlyAttendenceController: {
        add: `${apiPrfix}/monthly-attendence`,
        update: `${apiPrfix}/monthly-attendence`,
        delete: `${apiPrfix}/monthly-attendence/`,
        get: `${apiPrfix}/monthly-attendence/get/`,
        getAll: `${apiPrfix}/monthly-attendence`,
        search: `${apiPrfix}/monthly-attendence/search`,
        getByEmpId: `${apiPrfix}/monthly-attendence/get/emp/`,
        getByEmpIdMonthYear: `${apiPrfix}/monthly-attendence/get/emp-month-year/`,
        getByMonthYear: `${apiPrfix}/monthly-attendence/get/month-year/`,
        addUpdateDailyAttendence: `${apiPrfix}/daily-attendence`,
        getDailyAttendence: `${apiPrfix}/get/daily-attendence`,
    },
    dropdownController: {
        jobTitle: `${apiPrfix}/dropdown/job-titles`,
        experies: `${apiPrfix}/dropdown/experties`,
        employee: `${apiPrfix}/dropdown/employees`,
        customerOrders: `${apiPrfix}/dropdown/customer-orders`,
        customers: `${apiPrfix}/dropdown/customers`,
        products: `${apiPrfix}/dropdown/products`,
        suppliers: `${apiPrfix}/dropdown/suppliers`,
        designCategory: `${apiPrfix}/dropdown/design-category`
    },
    masterDataController: {
        add: `${apiPrfix}/master-data`,
        update: `${apiPrfix}/master-data`,
        delete: `${apiPrfix}/master-data/`,
        get: `${apiPrfix}/master-data/get/`,
        getAll: `${apiPrfix}/master-data`,
        search: `${apiPrfix}/master-data/search`,
        getByMasterDataType: `${apiPrfix}/master-data/get/by-type`,
        getByMasterDataTypes: `${apiPrfix}/master-data/get/by-types`,
        addDataType: `${apiPrfix}/master-data-type`,
        updateDataType: `${apiPrfix}/master-data-type`,
        deleteDataType: `${apiPrfix}/master-data-type/`,
        getDataType: `${apiPrfix}/master-data-type/get/`,
        getAllDataType: `${apiPrfix}/master-data-type`,
        searchDataType: `${apiPrfix}/master-data-type/search`,
    },
    masterController: {
        designCategory: {
            add: `${apiPrfix}/design-category`,
            update: `${apiPrfix}/design-category`,
            delete: `${apiPrfix}/design-category/`,
            search: `${apiPrfix}/design-category/search`,
            get: `${apiPrfix}/design-category/get/`,
            getAll: `${apiPrfix}/design-category`
        },
        designSample: {
            add: `${apiPrfix}/design-sample`,
            update: `${apiPrfix}/design-sample`,
            delete: `${apiPrfix}/design-sample/`,
            search: `${apiPrfix}/design-sample/search`,
            get: `${apiPrfix}/design-sample/get/`,
            getAll: `${apiPrfix}/design-sample`,
            getByDesignCategory: `${apiPrfix}/design-sample/get/category/`
        },
        jobTitle: {
            add: `${apiPrfix}/job-title`,
            update: `${apiPrfix}/job-title`,
            delete: `${apiPrfix}/job-title/`,
            search: `${apiPrfix}/job-title/search`,
            get: `${apiPrfix}/job-title/get/`,
            getAll: `${apiPrfix}/job-title`
        },
        kandooraHead:{
            add: `${apiPrfix}/master-data/kandoora/head`,
            update: `${apiPrfix}/master-data/kandoora/head`,
            delete: `${apiPrfix}/master-data/kandoora/head/`,
            search: `${apiPrfix}/master-data/kandoora/head/search`,
            get: `${apiPrfix}/master-data/kandoora/head/get/`,
            getAll: `${apiPrfix}/master-data/kandoora/head`
        },
        kandooraExpense:{
            add: `${apiPrfix}/master-data/kandoora/expense`,
            getAllExpenseSum: `${apiPrfix}/master-data/kandoora/expense/get/sum`,
            getAll: `${apiPrfix}/master-data/kandoora/expense`
        }
    },
    orderController:{
        add: `${apiPrfix}/orders`,
        update: `${apiPrfix}/orders`,
        delete: `${apiPrfix}/orders/`,
        get: `${apiPrfix}/orders/get/`,
        getAll: `${apiPrfix}/orders`,
        search: `${apiPrfix}/orders/search`,
        searchCancelledOrders: `${apiPrfix}/orders/search/cancelled-orders`, 
        searchDeletedOrders: `${apiPrfix}/orders/search/deleted-orders`,
        searchPendingOrders: `${apiPrfix}/orders/search/pending-orders`,

        searchByCustomer: `${apiPrfix}/orders/search/by-customer`,
        searchBySalesman: `${apiPrfix}/orders/search/by-salesman`,
        searchBySalesmanAndDateRange: `${apiPrfix}/orders/search/by-salesman/`, 
        getBySalesmanAndDateRange:`${apiPrfix}/orders/get/by-salesman/`,

        getOrderNo:`${apiPrfix}/orders/get/order-no`,
        cancelOrder: `${apiPrfix}/orders/cancel/order`,
        cancelOrderDetail: `${apiPrfix}/orders/cancel/order-detail`,
        getPreviousAmount:`${apiPrfix}/orders/get/previous-amount`,
        getCustomerMeasurement:`${apiPrfix}/orders/get/customer-measurement`,
        getCustomerMeasurements:`${apiPrfix}/orders/get/customer-measurements`,
        getCancelledOrder:`${apiPrfix}/orders/get/cancelled-orders`,
        getDeletedOrder:`${apiPrfix}/orders/get/deleted-orders`,
        getPendingOrder:`${apiPrfix}/orders/get/pending-orders`,
        getByCustomer:`${apiPrfix}/orders/get/by-customer`,
        getBySalesman:`${apiPrfix}/orders/get/by-salesman`,
        getByDeliveryDate:`${apiPrfix}/orders/get/delivery-date/`,
        getByOrderNumber:`${apiPrfix}/orders/get/order-nos`,
        getOrderDetails:`${apiPrfix}/orders/get/order-details`,
        getOrderAlert:`${apiPrfix}/orders/get/order-alerts?AlertBeforeDays=`,
        searchAlert:`${apiPrfix}/orders/search/alert?`,
        updateMeasurement:`${apiPrfix}/orders/update/measurement`,
        updateDeliveryPayment:`${apiPrfix}/orders/update/delivery-payment`,
        updateDesignModel:`${apiPrfix}/orders/update/design-model/`,
        updateOrderDate:`${apiPrfix}/orders/update/order-date/`,
        getCustomerPaymentForOrder:`${apiPrfix}/orders/get/customer/payment?orderId=`,
        getSampleCountInPreOrder:`${apiPrfix}/orders/get/sample/count?customerId=`,
        getAdvancePaymentStatement:`${apiPrfix}/orders/get/customer/payment/statement?orderId=`,
        getOrdersQty:`${apiPrfix}/orders/get/order-qty`
    },
    purchaseEntryController:{
        add: `${apiPrfix}/purchase-entry`,
        update: `${apiPrfix}/purchase-entry`,
        delete: `${apiPrfix}/purchase-entry/`,
        get: `${apiPrfix}/purchase-entry/get/`,
        getAll: `${apiPrfix}/purchase-entry`,
        search: `${apiPrfix}/purchase-entry/search`,
        getPurchaseNo:`${apiPrfix}/purchase-entry/get/purchase-no`,
    },
    workTypeStatusController:{
        update: `${apiPrfix}/work-type-status`,
        get: `${apiPrfix}/work-type-status`,
        getByOrderId: `${apiPrfix}/work-type-status/get/by/order-id?orderId=`,
        getSumAmount:`${apiPrfix}/work-type-status/get/sum-amount`
    },
    fileStorageController:{
        uploadFile:`${apiPrfix}/file-upload`, 
        getFileByModuleIdsAndName:`${apiPrfix}/file-storage/module-ids/`,
    }
}